### ISSUE TITLE
how are network disconnects handled?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-error-logging#13]
It seems like a fairly common occurrence for a user to walk a laptop between networks or turn on airport mode. Are these propogated?

**Comment by igrigorik** [comment]
I think this a subset of #25. I'd propose the following behavior:

* If the browser knows its currently offline ([navigator.onLine](https://html.spec.whatwg.org/#navigator.online) reports `false`), then we shouldn't fire an error report: the failure is not unexpected behavior and it should be the responsibility of the UA to communicate to the user that they are currently offline and network loads will fail.
* If the browser thinks its currently online (navigator.onLine returns `true`) but the load fails, then we should report an NEL error.

This allows us to punt the responsibility to detect/monitor network state to navigator.onLine, and allows the UA to improve its logic for how it does so independent of NEL.

**Comment by toddreifsteck** [comment]
Agreed. Closing as a subset of #25
