### ISSUE TITLE
client-side type filtering

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-error-logging#15]
I can imagine a service not being interested in particular subclasses of events. Should we provide a filter if a site is only interested in dns/tls but isn't interested in tcp/other?

**Comment by igrigorik** [comment]
What's a real-world use case where this would be the case? It seems really odd to me to track DNS+TLS but then ignore TCP errors. I think this has the danger of then devolving to: I want to specify different policies for different types of errors, etc.. Which I'd prefer to avoid to keep both the spec and deployment story simple.

**Comment by toddreifsteck** [comment]
I think most scenarios that I'm gut checking here will be resolved by improving our definition of a Navigation Error to exclude disconnected networks.
