### ISSUE TITLE
Protocol assumes HTTP

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-error-logging#18]
Does the spec need to generalize for other possible protocols?

**Comment by igrigorik** [comment]
Are you referring to `http.____` error codes? What would be an example of alternative protocol? Note that the spec doesn't restrict the UA to just the specified error types:

> The user agent may extend the above error type list with custom values - e.g. new error types to accommodate new protocols, or more detailed error descriptions of existing ones.

**Comment by toddreifsteck** [comment]
This was due to a typo on internal feedback from another team member. Sorry for burning cycles.
