### ISSUE TITLE
extensions to NEL directives

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-error-logging#22]
Do we need to reserve a prefix for the standard or is it ok to leave things open?

**Comment by igrigorik** [comment]
None of the specced directives use a prefix, and their use is contained to the NEL header value, so I don't think we need to worry this.

**Comment by igrigorik** [comment]
Closing, feel free to reopen if I misunderstood the intent :)

**Comment by toddreifsteck** [comment]
New guy just wanted to clarify intent
