### ISSUE TITLE
extensions to error codes

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-error-logging#23]
Do we need to reserve any for standard?

**Comment by igrigorik** [comment]
Are you referring to `type` field in the NEL-report? Because if so, then we do have language to allow UAs to extend the list: "The user agent may extend the above error type list with custom values - e.g. new error types to accommodate new protocols, or more detailed error descriptions of existing ones."

**Comment by toddreifsteck** [comment]
Yes.. Sorry for not being specific in my feedback. The question was really whether we need to be concerned with multiple UAs extending the type list forcing us to come back to a standards conversation about extending the standards list. We have choices here:
1. Current--Allow UAs to do whatever they want. If UAs end up making same types mean different things, reporting services can parse them based on POST UA string.
2. Reserve a prefix for UAs
3. Reserve a prefix for standard extensions

**Comment by igrigorik** [comment]
@toddreifsteck see: https://github.com/w3c/navigation-error-logging/commit/03751e1895ebd2d1b81afd202597321bc544e6c1 - how does that look? 

Re, vendor prefixes: the general guidance is to [avoid them](http://www.chromium.org/blink#vendor-prefixes). That said, if there are UA specific errors, I don't think it's unreasonable for a UA to define a UA specific group.. but I'm not sure we need to cover that in the spec as the decision is highly context specific.

**Comment by toddreifsteck** [comment]
Thanks for updating. In general, I think the current set of error codes will need to be re-validated when implementers other than Chrome work on NEL but this is a good start at defining the shape.

**Comment by igrigorik** [comment]
Agreed, I'm sure we'll need to revisit those as we all get closer to implementation (which, hopefully, is not too far away :)). Closing this, let's take that discussion into new issues once the time comes.
