### ISSUE TITLE
What is a navigation error?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-error-logging#25]
We should define a navigation error a bit more clearly. 2xx/3xx is not a navigation error. Is a 500 a navigation error? What about a 502? They could both fall into the category of possibly diagnosable issues that this spec is intended to diagnose if they come from networking intfrastructure.

**Comment by toddreifsteck** [comment]
What about i-frames/sub-frames?
What about redirect chains?

**Comment by igrigorik** [comment]
I have a branch with a first cut at defining "network error": https://github.com/w3c/navigation-error-logging/compare/gh-pages...define-error

I believe it should cover all of the above issues... That said, anything I'm forgetting, or that should be reconsidered?
