### ISSUE TITLE
Please add POST ReportUri to all examples

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-error-logging#26]

**Comment by igrigorik** [comment]
Hmm, do you mean be more explicit in [2.4.2](https://w3c.github.io/navigation-error-logging/#sample-navigation-error-report) that "send" means "POST to specified report-uri"? In 2.4.1 we cover definitions only, which is a response header.

**Comment by toddreifsteck** [comment]
This was internal feedback. Upon review, I can now see that 2.4.1 specifies the POST uri that will be used. Thanks!
